name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # agente en el cual se ejecuta
    container: python:3.9-slim # imagen del contenedor
